from setuptools import setup

setup(
    name='LIFEsim',
    version='0.1.2',
    description='Simulator software for the Large Interferometer For Exoplanets (LIFE)',
    long_description=open('README.rst').read(),
    long_description_content_type='text/x-rst',
    author='Felix Dannert, Maurice Ottiger & Sascha Quanz',
    author_email='fdannert@ethz.ch',
    url='https://github.com/fdannert/LIFEsim',
    project_urls={'Documentation': 'https://pynpoint.readthedocs.io'},
    packages=['lifesim',
              'lifesim.core',
              'lifesim.gui',
              'lifesim.instrument',
              'lifesim.optimize',
              'lifesim.util'],
    include_package_data=True,
    install_requires=['astropy~=4.2',
                      'matplotlib~=3.3.3',
                      'numpy~=1.19.5',
                      'pandas~=1.2.0',
                      'PyQt5~=5.15.2',
                      'tqdm~=4.56.0',
                      'spectres'],
    dependency_links=['https://github.com/fdannert/SpectRes.git#egg=spectres'],
    license='GPLv3',
    zip_safe=False,
    keywords='lifesim',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Astronomy',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
        'Natural Language :: English',
        'Programming Language :: Python :: 3.7',
    ]
)